apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-tensorflow-serving
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8080'
  containers:
  - args:
    - '--model_name={{`{{.Name}}`}}'
    - --port=9000
    - --rest_api_port=8080
    - --model_base_path=/mnt/models
    - --rest_api_timeout_in_ms=60000
    command:
    - /usr/bin/tensorflow_model_server
    image: {{ .Values.kserveTensorflowServing.kserveContainer.image.repository 
      }}:{{ .Values.kserveTensorflowServing.kserveContainer.image.tag }}
    name: kserve-container
    resources: {{- toYaml .Values.kserveTensorflowServing.kserveContainer.resources | nindent 6 }}
  protocolVersions: {{- toYaml .Values.kserveTensorflowServing.protocolVersions | nindent 2 }}
  supportedModelFormats: {{- toYaml .Values.kserveTensorflowServing.supportedModelFormats | nindent 2 }}
