apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-xgbserver
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: '8080'
  containers:
  - args:
    - '--model_name={{`{{.Name}}`}}'
    - --model_dir=/mnt/models
    - --http_port=8080
    - --nthread=1
    image: {{ .Values.kserveXgbserver.kserveContainer.image.repository 
      }}:{{ .Values.kserveXgbserver.kserveContainer.image.tag }}
    name: kserve-container
    resources: {{- toYaml .Values.kserveXgbserver.kserveContainer.resources | nindent 6 }}
  protocolVersions: {{- toYaml .Values.kserveXgbserver.protocolVersions | nindent 2 }}
  supportedModelFormats: {{- toYaml .Values.kserveXgbserver.supportedModelFormats | nindent 2 }}
