apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
spec:
{{- if .Values.katibMysql.persistence.storageClass }}
  storageClassName: {{ .Values.katibMysql.persistence.storageClass }}
{{- end }}
  accessModes:
  {{- if not (empty .Values.katibMysql.persistence.accessModes) }}
  {{- range .Values.katibMysql.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.katibMysql.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.katibMysql.persistence.size | quote }}