apiVersion: v1
data:
  config.yaml: |
    issuer: {{ .Values.dex.issuer }}
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    {{- range $index, $user := .Values.dex.staticPasswords }}
      - username: {{ $user.username }}
        email: {{ $user.username }}
        userID: {{ $user.username }}
        hash: {{ $user.password }}
    {{- end }}
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/authservice/oidc/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
kind: ConfigMap
metadata:
  name: dex
  namespace: auth