apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pvcviewer
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: pvc-viewer
  name: pvcviewer-controller-manager
  namespace: kubeflow
