apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kfp-poddefault-controller.fullname" . }}-config
  labels:
  {{- include "kfp-poddefault-controller.labels" . | nindent 4 }}
data:
  podDefaults: {{ .Values.config.podDefaults | toYaml | indent 1 }}