apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kfp-poddefault-controller.fullname" . }}-manager-role
  labels:
  {{- include "kfp-poddefault-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - poddefaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kfp-poddefault-controller.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kfp-poddefault-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kfp-poddefault-controller.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kfp-poddefault-controller.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'