aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      serving.knative.dev/controller: 'true'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.10.2
  name: knative-serving-admin
