apiVersion: v1
kind: Secret
metadata:
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: control-plane
  name: control-serving-certs
  namespace: knative-serving
