apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pvcviewer
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: pvc-viewer
  name: pvcviewer-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvcviewer-role
subjects:
- kind: ServiceAccount
  name: pvcviewer-controller-manager
  namespace: kubeflow
