apiVersion: v1
data:
  authentication.oidc: disabled
  delivery-retryafter: disabled
  delivery-timeout: enabled
  eventtype-auto-create: disabled
  kreference-group: disabled
  kreference-mapping: disabled
  new-trigger-filters: enabled
  transport-encryption: disabled
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.12.6
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
    kustomize.component: knative
  name: config-features
  namespace: knative-eventing
