apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: '{{ .Release.Namespace }}'
spec:
  match: {{- concat .Values.rafayExcludedNamespaces  .Values.excludedNamespaces | toYaml | nindent 4 }}
  {{- if .Values.sync }}
  sync:
  {{- .Values.sync | toYaml | nindent 4 }}
  {{- end }}