apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: fluent-bit-controller-config
  namespace: '{{ .Release.Namespace }}'
data:
  custom_parsers.conf: |-
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |-
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
    [INPUT]
        Name tail
        Path /var/log/containers/gatekeeper-controller*.log
        multiline.parser  docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
    [FILTER]
        Name modify
        Match *
        Rename message content
        Rename log content
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Merge_Log_Trim On
        Labels On
        Annotations Off
        K8S-Logging.Parser Off
        K8S-Logging.Exclude Off
    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix   kubernetes_
    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes_labels
        Add_prefix   rafay_
    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_container_name fluent-bit
    [FILTER]
        Name  grep
        Match kube.*
        Regex kubernetes_pod_name ${POD_NAME} 
    [FILTER]
        Name   grep
        Match  *
        Regex  content violation
    [FILTER]
        Name modify
        Match kube.*
        Rename log content
        Rename kubernetes_pod_name pod
        Rename kubernetes_namespace_name ns
        Remove kubernetes_container_image
        Remove kubernetes_docker_id
        Remove kubernetes_container_name
        Remove kubernetes_pod_id
        Remove kubernetes_host
        Remove time
        Remove kubernetes_container_hash
        Remove stream
    [FILTER]
        Name modify
        Match kube.*
        Remove rafay_app
        Remove _p
        Remove rafay_chart
        Remove rafay_control_plane
        Remove rafay_gatekeeper.sh/operation
        Remove rafay_gatekeeper.sh/system
        Remove rafay_heritage
        Remove rafay_pod-template-hash
        Remove rafay_release
        Remove rafay_rep-placement
        Remove rafay_rep-drift-reconcillation
        Rename rafay_control-plane cp
        Rename rafay_rep-organization on
        Rename rafay_rep-addon ad
        Rename rafay_rep-cluster cid
        Rename rafay_rep-cluster-name cn
        Rename rafay_rep-partner pt
        Rename rafay_rep-project pid
        Rename rafay_rep-project-name pr
        Rename rafay_rep-workloadid wl
        Rename rcloud.edge_id eid
    [FILTER]
        Name     throttle
        Match    kube.*
        Rate     5000
        Window   5
        Interval 30s
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule          $content  .*  opa  false
        Emitter_Name  re_emitted
    [OUTPUT]
        Name     http
        Match    opa
        Host     {{ .Values.fluentdAggr  }}
        URI      opa.logs
        Port     443
        tls      on
        tls.verify off
        tls.debug  verbose
        Retry_Limit     False
        Format     json
        
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On
        Decode_Field_As   escaped    content
    [PARSER]
        Name         json
        Format       json
        Time_Key     timestamp
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep    On
        Decode_Field_As   escaped    content
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z