apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: pvcviewer
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: pvc-viewer
  name: pvcviewer-selfsigned-issuer
  namespace: kubeflow
spec:
  selfSigned: {}
