apiVersion: v1
kind: Secret
metadata:
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane-routing
  name: routing-serving-certs
  namespace: istio-system
