apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: brokers.eventing.knative.dev
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
  annotations:
    duck.knative.dev/addressable: 'true'
    knative.dev/crd-install: 'true'
    kustomize.component: knative
spec:
  group: eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    kind: Broker
    plural: brokers
    singular: broker
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: Broker collects a pool of events that are consumable using Triggers.
          Brokers provide a well-known endpoint for event delivery that senders can
          use with minimal knowledge of the event routing strategy. Subscribers use
          Triggers to request delivery of events from a Broker's pool to a specific
          URL or Addressable endpoint.
        type: object
        properties:
          spec:
            description: Spec defines the desired state of the Broker.
            type: object
            properties:
              config:
                description: Config is a KReference to the configuration that specifies
                  configuration options for this Broker. For example, this could be
                  a pointer to a ConfigMap.
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
              delivery:
                description: Delivery contains the delivery spec for each trigger
                  to this Broker. Each trigger delivery spec, if any, overrides this
                  global delivery spec.
                type: object
                properties:
                  backoffDelay:
                    type: string
                  backoffPolicy:
                    type: string
                  deadLetterSink:
                    type: object
                    properties:
                      ref:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                          namespace:
                            type: string
                      uri:
                        type: string
                  retry:
                    type: integer
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status represents the current state of the Broker. This data
              may be out of date.
            type: object
            properties:
              address:
                type: object
                properties:
                  url:
                    type: string
              annotations:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    severity:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - status
              deadLetterSinkUri:
                type: string
              observedGeneration:
                type: integer
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.address.url
      name: URL
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
    - jsonPath: .metadata.annotations.eventing\.knative\.dev/broker\.class
      name: Class
      priority: 1
      type: string

