apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingsources.sources.knative.dev
  annotations:
    registry.knative.dev/eventTypes: |
      [
        {
          "type": "dev.knative.sources.ping",
          "description": "CloudEvent type for fixed payloads on a specified cron schedule"
        }
      ]
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: "1.12.6"
    duck.knative.dev/source: "true"
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
    kustomize.component: knative
spec:
  group: sources.knative.dev
  names:
    kind: PingSource
    plural: pingsources
    singular: pingsource
    categories:
      - all
      - knative
      - sources
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: eventing-webhook
          namespace: knative-eventing
      conversionReviewVersions:
        - v1
        - v1beta1
  versions:
    - name: v1beta2
      served: true
      storage: false
      additionalPrinterColumns:
        - jsonPath: .status.sinkUri
          name: Sink
          type: string
        - jsonPath: .spec.schedule
          name: Schedule
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          description: PingSource describes an event source with a fixed payload produced on a specified cron schedule.
          properties:
            spec:
              type: object
              description: PingSourceSpec defines the desired state of the PingSource.
              properties:
                schedule:
                  type: string
                  description: Schedule is the cron schedule. Defaults to `* * * * *`.
                data:
                  type: string
                  description: Data is the body of the event posted to the sink. Mutually exclusive with `dataBase64`.
                dataBase64:
                  type: string
                  description: Base64-encoded string of the event body posted to the sink.
                contentType:
                  type: string
                  description: Media type of the data or dataBase64. Default is empty.
                ceOverrides:
                  type: object
                  description: CloudEventOverrides for the event sent to the sink.
                  properties:
                    extensions:
                      type: object
                      additionalProperties:
                        type: string
                      description: Extensions to override CloudEvent attributes.
                sink:
                  type: object
                  description: Reference to an object resolving to a sink URI.
                  properties:
                    ref:
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    uri:
                      type: string
                      description: Absolute or relative URI for the sink.
                timezone:
                  type: string
                  description: Timezone for scheduling. Defaults to system timezone.
            status:
              type: object
              description: PingSourceStatus defines the observed state of the PingSource.
              properties:
                observedGeneration:
                  type: integer
                  description: Last processed generation.
                  format: int64
                sinkUri:
                  type: string
                  description: Active sink URI.
                conditions:
                  type: array
                  description: Observed conditions of the PingSource.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: Type of the condition.
                      status:
                        type: string
                        description: Status of the condition (True, False, Unknown).
                      reason:
                        type: string
                        description: Reason for the condition.
                      message:
                        type: string
                        description: Human-readable message about the condition.
                ceAttributes:
                  type: array
                  description: CloudEvent attributes.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: CloudEvent type.
                      source:
                        type: string
                        description: CloudEvent source.
                annotations:
                  type: object
                  description: Additional status fields.
                  x-kubernetes-preserve-unknown-fields: true
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.sinkUri
          name: Sink
          type: string
        - jsonPath: .spec.schedule
          name: Schedule
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          description: PingSource describes an event source with a fixed payload produced on a specified cron schedule.
          properties:
            spec:
              type: object
              description: PingSourceSpec defines the desired state of the PingSource.
              properties:
                schedule:
                  type: string
                  description: Schedule is the cron schedule. Defaults to `* * * * *`.
                data:
                  type: string
                  description: Data is the body of the event posted to the sink. Mutually exclusive with `dataBase64`.
                dataBase64:
                  type: string
                  description: Base64-encoded string of the event body posted to the sink.
                contentType:
                  type: string
                  description: Media type of the data or dataBase64. Default is empty.
                ceOverrides:
                  type: object
                  description: CloudEventOverrides for the event sent to the sink.
                  properties:
                    extensions:
                      type: object
                      additionalProperties:
                        type: string
                      description: Extensions to override CloudEvent attributes.
                sink:
                  type: object
                  description: Reference to an object resolving to a sink URI.
                  properties:
                    ref:
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    uri:
                      type: string
                      description: Absolute or relative URI for the sink.
                timezone:
                  type: string
                  description: Timezone for scheduling. Defaults to system timezone.
            status:
              type: object
              description: PingSourceStatus defines the observed state of the PingSource.
              properties:
                observedGeneration:
                  type: integer
                  description: Last processed generation.
                  format: int64
                sinkUri:
                  type: string
                  description: Active sink URI.
                conditions:
                  type: array
                  description: Observed conditions of the PingSource.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: Type of the condition.
                      status:
                        type: string
                        description: Status of the condition (True, False, Unknown).
                      reason:
                        type: string
                        description: Reason for the condition.
                      message:
                        type: string
                        description: Human-readable message about the condition.
                ceAttributes:
                  type: array
                  description: CloudEvent attributes.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: CloudEvent type.
                      source:
                        type: string
                        description: CloudEvent source.
                annotations:
                  type: object
                  description: Additional status fields.
                  x-kubernetes-preserve-unknown-fields: true
  subresources:
    status: {}
