apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sinkbindings.sources.knative.dev
  labels:
    app.kubernetes.io/component: knative-eventing
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: "1.12.6"
    duck.knative.dev/binding: "true"
    duck.knative.dev/source: "true"
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
    kustomize.component: knative
spec:
  group: sources.knative.dev
  names:
    kind: SinkBinding
    plural: sinkbindings
    singular: sinkbinding
    categories:
      - all
      - knative
      - sources
      - bindings
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.sinkUri
          name: Sink
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          description: >
            SinkBinding describes a Binding that is also a Source. The `sink`
            (from the Source duck) is resolved to a URL and then projected into the
            `subject` by augmenting the runtime contract of the referenced containers
            to have a `K_SINK` environment variable holding the endpoint to which to
            send cloud events.
          type: object
          properties:
            spec:
              type: object
              properties:
                ceOverrides:
                  description: >
                    CloudEventOverrides defines overrides to control the output format
                    and modifications of the event sent to the sink.
                  type: object
                  properties:
                    extensions:
                      description: >
                        Extensions specify what attributes are added or overridden
                        on the outbound event. Each `Extensions` key-value pair is
                        set on the event as an attribute extension independently.
                      type: object
                      additionalProperties:
                        type: string
                      x-kubernetes-preserve-unknown-fields: true
                sink:
                  description: >
                    Sink is a reference to an object that will resolve to a URI
                    to use as the sink.
                  type: object
                  properties:
                    ref:
                      type: object
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                    uri:
                      type: string
                      description: >
                        URI can be an absolute URL (non-empty scheme and non-empty
                        host) pointing to the target or a relative URI.
                subject:
                  description: >
                    Subject references the resource(s) whose "runtime contract"
                    should be augmented by Binding implementations.
                  type: object
                  properties:
                    apiVersion:
                      type: string
                      description: API version of the referent.
                    kind:
                      type: string
                      description: Kind of the referent.
                    name:
                      type: string
                      description: Name of the referent. Mutually exclusive with Selector.
                    namespace:
                      type: string
                      description: Namespace of the referent.
                    selector:
                      type: object
                      description: Selector of the referents. Mutually exclusive with Name.
                      properties:
                        matchLabels:
                          type: object
                          description: A map of {key,value} pairs to match labels.
                          x-kubernetes-preserve-unknown-fields: true
                        matchExpressions:
                          type: array
                          description: A list of label selector requirements. The requirements are ANDed.
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                type: array
                                items:
                                  type: string
            status:
              type: object
              properties:
                annotations:
                  type: object
                  description: >
                    Additional status fields for the resource to save extra state and
                    convey more information to the user.
                  x-kubernetes-preserve-unknown-fields: true
                ceAttributes:
                  type: array
                  description: CloudEventAttributes used by the source.
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                      type:
                        type: string
                conditions:
                  type: array
                  description: Observed conditions of the resource's state.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                sinkUri:
                  type: string
                  description: The resolved sink URI.
                observedGeneration:
                  type: integer
                  format: int64
                  description: The generation of the resource last processed by the controller.
  subresources:
    status: {}
