apiVersion: v1
kind: Service
metadata:
 name: patch-pod-runtime-class
 namespace: {{ .Values.admissionController.namespace }}
spec:
 ports:
   - name: https
     port: 7443
     targetPort: 7443
 selector:
   app: patch-pod-runtime-class
 type: ClusterIP