# Default values for cluster-local-gateway.
clusterLocalGateway:
  istioProxy:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    image:
      repository: docker.io/istio/proxyv2
      tag: 1.17.5
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi