config:
  podDefaults: |-
    kind: PodDefaultList
    apiVersion: kubeflow.org/v1alpha1
    metadata:
      resourceVersion: "1"
    items:
      - apiVersion: kubeflow.org/v1alpha1
        kind: PodDefault
        metadata:
          name: access-ml-pipeline
        spec:
          desc: Allow access to Kubeflow Pipelines
          selector:
            matchLabels:
              access-ml-pipeline: "true"
          volumes:
            - name: volume-kf-pipeline-token
              projected:
                sources:
                  - serviceAccountToken:
                      path: token
                      expirationSeconds: 7200
                      audience: pipelines.kubeflow.org
          volumeMounts:
            - mountPath: /var/run/secrets/kubeflow/pipelines
              name: volume-kf-pipeline-token
              readOnly: true
          env:
            - name: KF_PIPELINES_SA_TOKEN_PATH
              value: /var/run/secrets/kubeflow/pipelines/token
controllerManager:
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
manager:
  manager:
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: us-central1-docker.pkg.dev/rafay-labs/ai-ml-repo/kfp-poddefault-controller
      tag: 0.1.0
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  replicas: 1
