apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    katib.kubeflow.org/component: db-manager
  name: katib-db-manager
  namespace: kubeflow
spec:
  replicas: {{ .Values.katibDbManager.replicas }}
  selector:
    matchLabels:
      katib.kubeflow.org/component: db-manager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        katib.kubeflow.org/component: db-manager
    spec:
      containers:
      - command:
        - ./katib-db-manager
        env:
        - name: DB_NAME
          value: mysql
        - name: DB_USER
          value: {{ .Values.katibMysql.user }}
        - name: KATIB_MYSQL_DB_HOST
          value: {{ .Values.katibMysql.host }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: katib-mysql-secrets
        image: {{ .Values.katibDbManager.katibDbManager.image.repository }}:{{ .Values.katibDbManager.katibDbManager.image.tag }}
        livenessProbe:
          failureThreshold: 5
          grpc:
            port: 6789
          initialDelaySeconds: 10
          periodSeconds: 60
        name: katib-db-manager
        ports:
        - containerPort: 6789
          name: api
