apiVersion: v1
data:
  defaultTrialTemplate.yaml: {{ .Values.trialTemplates.defaultTrialTemplateYaml |
    toYaml | indent 1 }}
  enasCPUTemplate: {{ .Values.trialTemplates.enasCPUTemplate | toYaml | indent 1
    }}
  pytorchJobTemplate: {{ .Values.trialTemplates.pytorchJobTemplate | toYaml | indent
    1 }}
kind: ConfigMap
metadata:
  labels:
    katib.kubeflow.org/component: trial-templates
  name: trial-templates
  namespace: kubeflow
