apiVersion: v1
data:
  tls.crt: {{ .Values.istio.tls.cert }}
  tls.key: {{ .Values.istio.tls.key }}
kind: Secret
metadata:
  name: kubeflow-gateway-tls-certs
  namespace: istio-system
type: kubernetes.io/tls
