apiVersion: v1
data:
  ISTIO_GATEWAY: kubeflow/kubeflow-gateway
  RWO_PVC_SCHEDULING: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.rwoPvcScheduling
    | quote }}
  TENSORBOARD_IMAGE: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.tensorboardImage
    | quote }}
kind: ConfigMap
metadata:
  name: tensorboard-controller-config-b98cb9gk9k
  namespace: kubeflow
