# Default values for notebook-controller.
notebookControllerDeployment:
  manager:
    image:
      repository: docker.io/kubeflownotebookswg/notebook-controller
      tag: v1.8.0
    enableCulling: true
