apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: minio-pvc
  namespace: kubeflow
spec:
{{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
{{- end }}
  accessModes:
  {{- if not (empty .Values.minio.persistence.accessModes) }}
  {{- range .Values.minio.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.minio.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size | quote }}
