apiVersion: v1
kind: Service
metadata:
  labels:
    app: pvcviewer
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: pvc-viewer
  name: pvcviewer-webhook-service
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: pvcviewer
    control-plane: controller-manager
