apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kubeflow/pvcviewer-serving-cert
  labels:
    app: pvcviewer
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/part-of: pvc-viewer
  name: pvcviewer-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: pvcviewer-webhook-service
      namespace: kubeflow
      path: /mutate-kubeflow-org-v1alpha1-pvcviewer
  failurePolicy: Fail
  name: mpvcviewer.kb.io
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pvcviewers
  sideEffects: None
