apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.12.4
    serving.knative.dev/controller: 'true'
  name: knative-serving-activator
  namespace: knative-serving
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resourceNames:
  - routing-serving-certs
  - knative-serving-certs
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
