apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: pvcviewer
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: pvc-viewer
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: pvc-viewer
  name: pvcviewer-serving-cert
  namespace: kubeflow
spec:
  dnsNames:
  - pvcviewer-webhook-service.kubeflow.svc
  - pvcviewer-webhook-service.kubeflow.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pvcviewer-selfsigned-issuer
  secretName: webhook-server-cert
