apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kata-deploy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kata-deploy-role
subjects:
  - kind: ServiceAccount
    name: kata-deploy-sa
    namespace: {{ .Values.kataDeploy.namespace }}
