apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-qemu
handler: kata-qemu
overhead:
  podFixed:
    memory: 160Mi
    cpu: 250m
scheduling:
  nodeSelector:
    kubernetes.io/os: linux
