apiVersion: v1
data:
  ISTIO_GATEWAY: kubeflow/kubeflow-gateway
  ISTIO_HOST: '*'
  RWO_PVC_SCHEDULING: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.rwoPvcScheduling
    | quote }}
  TENSORBOARD_IMAGE: {{ .Values.tensorboardControllerConfigB98Cb9Gk9K.tensorboardImage
    | quote }}
kind: ConfigMap
metadata:
  name: tensorboard-controller-config-7hd244gf2d
  namespace: kubeflow
