# Default values for Katib.
katibConfig:
  katibConfigYaml: |-
    ---
    apiVersion: config.kubeflow.org/v1beta1
    kind: KatibConfig
    init:
      controller:
        webhookPort: 8443
        trialResources:
          - Job.v1.batch
          - TFJob.v1.kubeflow.org
          - PyTorchJob.v1.kubeflow.org
          - MPIJob.v1.kubeflow.org
          - XGBoostJob.v1.kubeflow.org
          - MXJob.v1.kubeflow.org
    runtime:
      metricsCollectors:
        - kind: StdOut
          image: docker.io/kubeflowkatib/file-metrics-collector:v0.17.0
        - kind: File
          image: docker.io/kubeflowkatib/file-metrics-collector:v0.17.0
        - kind: TensorFlowEvent
          image: docker.io/kubeflowkatib/tfevent-metrics-collector:v0.17.0
          resources:
            limits:
              memory: 1Gi
      suggestions:
        - algorithmName: random
          image: docker.io/kubeflowkatib/suggestion-hyperopt:v0.17.0
        - algorithmName: tpe
          image: docker.io/kubeflowkatib/suggestion-hyperopt:v0.17.0
        - algorithmName: grid
          image: docker.io/kubeflowkatib/suggestion-optuna:v0.17.0
        - algorithmName: hyperband
          image: docker.io/kubeflowkatib/suggestion-hyperband:v0.17.0
        - algorithmName: bayesianoptimization
          image: docker.io/kubeflowkatib/suggestion-skopt:v0.17.0
        - algorithmName: cmaes
          image: docker.io/kubeflowkatib/suggestion-goptuna:v0.17.0
        - algorithmName: sobol
          image: docker.io/kubeflowkatib/suggestion-goptuna:v0.17.0
        - algorithmName: multivariate-tpe
          image: docker.io/kubeflowkatib/suggestion-optuna:v0.17.0
        - algorithmName: enas
          image: docker.io/kubeflowkatib/suggestion-enas:v0.17.0
          resources:
            limits:
              memory: 200Mi
        - algorithmName: darts
          image: docker.io/kubeflowkatib/suggestion-darts:v0.17.0
        - algorithmName: pbt
          image: docker.io/kubeflowkatib/suggestion-pbt:v0.17.0
          persistentVolumeClaimSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 5Gi
      earlyStoppings:
        - algorithmName: medianstop
          image: docker.io/kubeflowkatib/earlystopping-medianstop:v0.17.0
# Default values for Katib Controller.
katibController:
  replicas: 1
  katibController:
    image:
      repository: docker.io/kubeflowkatib/katib-controller
      tag: v0.17.0
trialTemplates:
  defaultTrialTemplateYaml: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
            - name: training-container
              image: docker.io/kubeflowkatib/mxnet-mnist:v0.17.0
              command:
                - "python3"
                - "/opt/mxnet-mnist/mnist.py"
                - "--batch-size=64"
                - "--lr=${trialParameters.learningRate}"
                - "--num-layers=${trialParameters.numberLayers}"
                - "--optimizer=${trialParameters.optimizer}"
          restartPolicy: Never
  enasCPUTemplate: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
            - name: training-container
              image: docker.io/kubeflowkatib/enas-cnn-cifar10-cpu:v0.17.0
              command:
                - python3
                - -u
                - RunTrial.py
                - --num_epochs=1
                - "--architecture=\"${trialParameters.neuralNetworkArchitecture}\""
                - "--nn_config=\"${trialParameters.neuralNetworkConfig}\""
          restartPolicy: Never
  pytorchJobTemplate: |-
    apiVersion: kubeflow.org/v1
    kind: PyTorchJob
    spec:
      pytorchReplicaSpecs:
        Master:
          replicas: 1
          restartPolicy: OnFailure
          template:
            spec:
              containers:
                - name: pytorch
                  image: docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.17.0
                  command:
                    - "python3"
                    - "/opt/pytorch-mnist/mnist.py"
                    - "--epochs=1"
                    - "--lr=${trialParameters.learningRate}"
                    - "--momentum=${trialParameters.momentum}"
        Worker:
          replicas: 2
          restartPolicy: OnFailure
          template:
            spec:
              containers:
                - name: pytorch
                  image: docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.17.0
                  command:
                    - "python3"
                    - "/opt/pytorch-mnist/mnist.py"
                    - "--epochs=1"
                    - "--lr=${trialParameters.learningRate}"
                    - "--momentum=${trialParameters.momentum}"
# Default values for Katib DB Manager.
katibDbManager:
  replicas: 1
  katibDbManager:
    image:
      repository: docker.io/kubeflowkatib/katib-db-manager
      tag: v0.17.0
# Default values for Katib Mysql.
katibMysql:
  host: katib-mysql
  port: 3306
  user: root
  password: katib #base64 encoded password
  replicas: 1
  katibMysql:
    image:
      repository: mysql
      tag: 8.0.29
# Default values for Katib UI.
katibUi:
  replicas: 1
  katibUi:
    image:
      repository: docker.io/kubeflowkatib/katib-ui
      tag: v0.17.0
