apiVersion: v1
data:
  OIDC_CLIENT_ID: {{ required "dexOidcClient.oidcClientId is required" .Values.dexOidcClient.oidcClientId
    | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ required "dexOidcClient.oidcClientSecret is required" .Values.dexOidcClient.oidcClientSecret
    | b64enc | quote }}
kind: Secret
metadata:
  name: dex-oidc-client
  namespace: auth
type: Opaque
